name: Packer Build and Artifact Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest test_main.py
        env:
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: webapp_db

      - name: Create build directory and package app
        run: |
          mkdir -p build_output
          tar -czvf build_output/app_binary.tar.gz main.py
          # Check if the tarball was successfully created
          if [ ! -f build_output/app_binary.tar.gz ]; then
            echo "Error: app_binary.tar.gz not found!"
            exit 1
          fi

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.11.2'

      - name: Initialize Packer
        run: |
          packer init webapp.pkr.hcl

      - name: Validate Packer template
        run: |
          packer validate webapp.pkr.hcl

      - name: Build Packer image
        run: |
          packer build webapp.pkr.hcl