name: Packer Build and Artifact Integration

on:
  push:
    branches:
      - main  # Runs only after PR is merged

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start

      - name: Set up test database
        run: |
          sudo -u postgres psql -c "CREATE USER testuser WITH PASSWORD 'testpassword';"
          sudo -u postgres psql -c "CREATE DATABASE webapp_db OWNER testuser;"

      - name: Run integration tests
        run: |
          pytest test_main.py
        env:
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: webapp_db

      - name: Build application artifact
        run: |
          mkdir -p build_output
          tar -czvf build_output/app_binary.tar.gz main.py requirements.txt
          if [ ! -f build_output/app_binary.tar.gz ]; then
            echo "Error: app_binary.tar.gz not found!"
            exit 1
          fi

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.11.2'

      # Configure AWS Credentials for DEV account (where AMI is built)
      - name: Configure AWS Credentials (DEV)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-profile: dev
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Packer
        run: |
          packer init webapp.pkr.hcl

      - name: Validate Packer template
        run: |
          packer validate webapp.pkr.hcl

      - name: Build Packer image (DEV)
        run: |
          packer build webapp.pkr.hcl

      # Share the AMI with the DEMO account
      - name: Share AMI with DEMO account
        run: |
          AMI_ID=$(packer build -machine-readable webapp.pkr.hcl | awk -F, '/artifact,0,id/ {print $6}')
          echo "Built AMI ID: $AMI_ID"
          aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "{\"Add\":[{\"UserId\":\"715841348526\"}]}"
        env:
          AWS_PROFILE: demo