name: Packer CI

on:
  pull_request:
    branches:
      - main  

jobs:
  packer-ci:
    name: Packer Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest test_main.py
        env:
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: webapp_db

      - name: Create app_binary.tar.gz
        run: |
          mkdir -p build_output
          tar -czvf build_output/app_binary.tar.gz main.py

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.11.2'

      - name: Run packer init to initialize plugins
        run: |
          packer init webapp.pkr.hcl
        continue-on-error: false

      - name: Run packer fmt to check formatting
        run: |
          packer fmt -check -recursive .
        continue-on-error: false

      - name: Run packer validate to validate template
        run: |
          packer validate webapp.pkr.hcl
        continue-on-error: false

      - name: Clean up build output
        run: |
          rm -rf build_output