name: Packer Build and Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.11.2'

      - name: Run packer fmt
        run: |
          packer fmt -check -diff webapp.pkr.hcl
        # Fail if fmt modified the template
        continue-on-error: false

      - name: Run packer validate
        run: |
          packer validate webapp.pkr.hcl
        continue-on-error: false