name: testing python code

on:
  push:
    branches:
      - main

jobs:
  build-test:
              runs-on: ubuntu-22.04

              steps:
              - name: Checkout code
                uses: actions/checkout@v3

              - name: Set up Python
                uses: actions/setup-python@v4
                with:
                  python-version: '3.11'

              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest pytest-mock

              - name: Set up environment variables
                run: |
                  echo "DB_USER=test_user" >> $GITHUB_ENV
                  echo "DB_PASSWORD=test_password" >> $GITHUB_ENV
                  echo "DB_HOST=localhost" >> $GITHUB_ENV
                  echo "DB_PORT=5432" >> $GITHUB_ENV
                  echo "DB_NAME=test_db" >> $GITHUB_ENV

              - name: Run Unit Tests
                run: |
                  pytest --maxfail=5 --disable-warnings